apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-airbyte

resources:
  - ../../base
  - configmap.yaml

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/metadata/namespace
        value: prod-airbyte
  - target:
      kind: Service
    patch: |
      - op: replace
        path: /metadata/namespace
        value: prod-airbyte
