{
 "title": "Airbyte Staging",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Infrastructure Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"stg-airbyte\"}[5m])) / sum(container_spec_cpu_quota{namespace=\"stg-airbyte\"}/container_spec_cpu_period{namespace=\"stg-airbyte\"}) * 100)"
    }
   ]
  },
  {
   "title": "Average CPU usage per pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"stg-airbyte\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Total Memory Usage (GB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"stg-airbyte\"}) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Maximum Memory Usage Per Container (GB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(container_memory_max_usage_bytes{namespace=\"stg-airbyte\"}[5m])) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=\"stg-airbyte\"}) / sum(container_spec_memory_limit_bytes{namespace=\"stg-airbyte\"} > 0) * 100)"
    }
   ]
  },
  {
   "title": "Total Network Receive and Transmit (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"stg-airbyte\"}[5m])) / 1024 / 1024",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"stg-airbyte\"}[5m])) / 1024 / 1024",
     "legendFormat": "Received"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number of Running Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stg_airbyte_num_running_jobs{kubernetes_namespace=\"stg-airbyte\",attempt_queue=\"SYNC\"}"
    }
   ]
  },
  {
   "title": "Age of oldest running job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "stg_airbyte_oldest_running_job_age_secs{attempt_queue=\"SYNC\"}"
    }
   ]
  },
  {
   "title": "Time since last heartbeat per connection (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stg_airbyte_source_time_since_last_heartbeat_millis_sum{kubernetes_namespace=\"stg-airbyte\"}[5m]) / rate(stg_airbyte_source_time_since_last_heartbeat_millis_count{kubernetes_namespace=\"stg-airbyte\"}[5m]) / 1000",
     "legendFormat": "{{ connection_id }}"
    }
   ]
  },
  {
   "title": "Number of successful sync workflows in the last day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(stg_airbyte_temporal_workflow_success_total{kubernetes_namespace=\"stg-airbyte\"}[24h])",
     "legendFormat": "{{ connection_id }}"
    }
   ]
  },
  {
   "title": "Number of replication activities performed in last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(stg_airbyte_activity_replication_total[1h])"
    }
   ]
  },
  {
   "title": "Number of workflow failures in the last day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(stg_airbyte_temporal_workflow_failure_total{kubernetes_namespace=\"stg-airbyte\"}[24h])",
     "legendFormat": "{{ connection_id }}"
    }
   ]
  },
  {
   "title": "Number of orphan running jobs",
   "type": "graph",
   "description": "Number of jobs reported as running that as associated to connection inactive or deprecated",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stg_airbyte_num_orphan_running_jobs"
    }
   ]
  },
  {
   "title": "Number of Unusually Long Syncs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stg_airbyte_num_unusually_long_syncs"
    }
   ]
  },
  {
   "title": "Average duration to create a new kube pod process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stg_airbyte_kube_pod_process_create_time_millisecs_sum{kubernetes_namespace=\"stg-airbyte\"}[5m]) / rate(stg_airbyte_kube_pod_process_create_time_millisecs_count{kubernetes_namespace=\"stg-airbyte\"}[5m]) / 1000",
     "legendFormat": "{{ exported_job }}"
    }
   ]
  },
  {
   "title": "Number of abnormal scheduled syncs in last day",
   "type": "graph",
   "description": "Number of abnormal syncs that have skipped at least 1 scheduled run in last day.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stg_airbyte_num_abnormal_scheduled_syncs_last_day"
    }
   ]
  },
  {
   "title": "Average run time of jobs in the last hour by status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(stg_airbyte_overall_job_runtime_in_last_hour_by_terminal_state_secs_sum{kubernetes_namespace=\"stg-airbyte\"}[1h]) / rate(stg_airbyte_overall_job_runtime_in_last_hour_by_terminal_state_secs_count{kubernetes_namespace=\"stg-airbyte\"}[1h])",
     "legendFormat": "{{ job_status }}"
    }
   ]
  },
  {
   "title": "Connection checks performed in last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(stg_airbyte_activity_check_connection_total[1h])"
    }
   ]
  },
  {
   "title": "Normalization activities performed in last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(stg_airbyte_activity_normalization_total[1h])"
    }
   ]
  },
  {
   "title": "Number of active connections per workspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stg_airbyte_num_active_conn_per_workspace_sum{kubernetes_namespace=\"stg-airbyte\"}[5m]) / rate(stg_airbyte_num_active_conn_per_workspace_count{kubernetes_namespace=\"stg-airbyte\"}[5m])"
    }
   ]
  },
  {
   "title": "Number of pending jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stg_airbyte_num_pending_jobs{kubernetes_namespace=\"stg-airbyte\"}",
     "legendFormat": "{{ geography }}"
    }
   ]
  },
  {
   "title": "Age of oldest pending job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(stg_airbyte_oldest_pending_job_age_secs{kubernetes_namespace=\"stg-airbyte\"})"
    }
   ]
  }
 ]
}